[platformio]
default_envs = nodemcu-32s

[env:nodemcu-32s]
platform = espressif32@6.10.0
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_type = release
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wpedantic
    -Werror=return-type
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    paulstoffregen/Encoder@^1.4.4
