controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false

diff_drive_controller:
  ros__parameters:
    left_wheel_names:
      - left_wheel_joint
    right_wheel_names:
      - right_wheel_joint

    wheel_separation: __WHEEL_SEPARATION__
    wheel_radius: __WHEEL_RADIUS__

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true

    pose_covariance_diagonal:
      - 0.001
      - 0.001
      - 1000000.0
      - 1000000.0
      - 1000000.0
      - 0.01

    twist_covariance_diagonal:
      - 0.001
      - 0.001
      - 1000000.0
      - 1000000.0
      - 1000000.0
      - 0.01

    open_loop: false
    position_feedback: true

    cmd_vel_timeout: 0.25
    publish_limited_velocity: true
    velocity_rolling_window_size: 10
    publish_rate: 50.0

    linear.x.max_velocity: __MAX_LINEAR_VELOCITY__
    linear.x.min_velocity: __MIN_LINEAR_VELOCITY__
    linear.x.max_acceleration: __MAX_LINEAR_ACCELERATION__
    linear.x.max_deceleration: __MAX_LINEAR_DECELERATION__
    linear.x.max_acceleration_reverse: __MAX_LINEAR_ACCELERATION_REVERSE__
    linear.x.max_deceleration_reverse: __MAX_LINEAR_DECELERATION_REVERSE__
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: __MAX_ANGULAR_VELOCITY__
    angular.z.min_velocity: __MIN_ANGULAR_VELOCITY__
    angular.z.max_acceleration: __MAX_ANGULAR_ACCELERATION__
    angular.z.max_deceleration: __MAX_ANGULAR_DECELERATION__
    angular.z.max_acceleration_reverse: __MAX_ANGULAR_ACCELERATION_REVERSE__
    angular.z.max_deceleration_reverse: __MAX_ANGULAR_DECELERATION_REVERSE__
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN
